# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Jekyll settings
# 4. Collections
# 5. Jekyll collections settings
# 6. Site settings
# 7. Site favicons and manifest icons
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude: 
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE.*
- SECURITY.md
- CNAME
- Gemfile
- Gemfile.lock
- gcweb-jekyll.gemspec
- .jekyll-cache
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- .github

# 2. Installed Gems
plugins: 
  - jekyll-remote-theme

# 3. Jekyll settings
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
quiet: false
permalink: pretty  # Permalink style (/page-name/)
remote_theme: wet-boew/gcweb-jekyll
timezone: America/Toronto # Timezone for blog posts and alike
themeJS: true
verbose: true

# 4. Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Jekyll variant for GCweb theme" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 5. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 6. Site settings
assets: "https://wet-boew.github.io/themes-dist"
encoding: utf-8 # Make sure the encoding is right
lang: en-CA # Set the site language
title: "gcweb-jekyll" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Jekyll variant for GCweb theme" # Site description and default description, also used in jekyll-seo-tag
url: "https://canada.ca" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/wet-boew/gcweb-jekyll"
email: " "
# disqus: " " # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
theme-name: GCWeb

# 7. Site favicons and manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  # 16: '/assets/logos/logo@16px.png'
  # 32: '/assets/logos/logo@32px.png'
  # 96: '/assets/logos/logo@96px.png'
  # 120: '/assets/logos/logo@120px.png'
  # 144: '/assets/logos/logo@144px.png'
  # 180: '/assets/logos/logo@180px.png'
  # 512: '/assets/logos/logo@512px.png'
  # 1024: '/assets/logos/logo@1024px.png'

# 8. Site navigation
navigation_header:
- title: Home
  url: /

navigation_footer:
- title: 
  url: 

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/[username]
  LinkedIn: https://www.linkedin.com/in/[username]
  GitHub: https://github.com/[username]
  link: https://canada.ca
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: false