backend:
  name: git-gateway
  branch: backend # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Pages in English"
    name: "english_pages"
    folder: "_pages/en"
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "French equivalent", name: "altLangFile", widget: "string"}
  - label: "Pages en français"
    name: "french_pages"
    folder: "_pages/fr"
    filter: {field: "language", value: "fr"}
    fields:
      - {label: "Langue", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Équivalent en anglais", name: "altLangFile", widget: "string"}
