backend:
  name: "git-gateway"
  branch: "backend" # Branch to update (optional; defaults to master)
  open_authoring: true

# This line should *not* be indented
publish_mode: "editorial_workflow"
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Pages in English"
    name: "pages-en"
    folder: "_pages/en"
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "French equivalent", name: "altLangFile", widget: "string"}
  - label: "Pages en français"
    name: "pages-fr"
    folder: "_pages/fr"
    filter: {field: "language", value: "fr"}
    fields:
      - {label: "Langue", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Équivalent en anglais", name: "altLangFile", widget: "string"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/content/home.yml"
        fields:
          - {label: "Title", name: "contentTitle", widget: "string"}
          - {label: "Byline", name: "byline", widget: "markdown"}
          - {label: "Most requested", name: "tmpl-most-requested-item", widget: "array"}
          - label: "Team"
            name: "team"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Photo", name: "photo", widget: "image"}
      - label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - label: "Locations"
            name: "locations"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Address", name: "address", widget: "string"}